---
# Title: Backup MySQL or MariaDB
#
# Author: Bitfinity-NL / L.Rutten
# File: tasks/main.yml
#
# Description:
#   Role that schedules a backup for MySQL databases.

- name: "Transfer template .my.cnf.j2 to /root/.my.cnf (Set user permissions)"
  template:
    src: .my.cnf.j2
    dest: /root/my.cnf
    owner: root
    group: root
    mode: 0600

- name: "Create directory structure for creating mysql backups"
  file:
    path: /opt/backup/mysql
    state: directory
    owner: root
    group: root
    mode: 0600

- name: "Transfer backup script to host"

- name: "Schedule backup script"
    
