---
# Title: Backup MySQL or MariaDB
#
# Author: Bitfinity-NL / L.Rutten
# File: tasks/main.yml
#
# Description:
#   Role that schedules a backup for MySQL databases.

- name: "Transfer template .my.cnf.j2 to /root/.my.cnf (Set user permissions)"
  template:
    src: .my.cnf.j2
    dest: /root/my.cnf
    owner: root
    group: root
    mode: 0600

- name: "Create directory structure for creating mysql backups"
  file:
    path: /opt/backup/mysql
    state: directory
    owner: root
    group: root
    mode: 0600

- name: "Transfer backup script to host"
  template:
     src: backup_db.sh.j2
     dest: /root/backup_db.sh
     owner: root
     group: root
     mode: 0700
   
- name: "Schedule backup script"
  cron:
    name: "Schedule database backup daily at 05 minutes past 0:00"
    minute: "5"
    hour: "0"
    job: "cd /root/ ; backup_db.sh >/dev/null 2>&1"
